name: Mark stale issues
on:
  schedule:
  - cron: "0 */8 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 7 days with no activity.'
        days-before-stale: 7
        days-before-close: 3
        exempt-issue-labels: 'bug,11.x-dev'
        exempt-pr-labels: 'bug,frozen,11.x-dev'
